image: docker-hub.program.com.tw/bikonnect-pluspay/php8.1-mongodb:dev

stages:
  - test

cs_fixer:
  stage: test
  tags:
    - docker
  script:
    - phpcbf --standard=PSR12 --exclude=Generic.Files.LineLength,PSR12.Classes.OpeningBraceSpace --extensions=php app
