image: docker-hub.program.com.tw/bikonnect-pluspay/php8.1-mongodb:dev

stages:
  - test

cs_test:
  stage: test
  tags:
    - docker
  before_script:
  - apt-get update
  - apt-get install -y ssh
  script:
    - echo "$ACCESS_TOKEN"
    - echo $ACCESS_TOKEN
    - php-cs-fixer fix app/
    - git config user.email "james.huang@program.com.tw"
    - git config user.name "james.huang"
    - git remote remove ssh_origin || true
    - git remote add ssh_origin https://oauth2:orU1_WyLzzJWuABdxhc9@gitlab1.program.com.tw/BackendGroup/freshman/now/202307-james/comment.git
    - git pull ssh_origin ci_test
    - git add .
    - git commit -m "push back from pipeline"
    - git push ssh_origin ci_test -o ci.skip
    # https://oauth2:orU1_WyLzzJWuABdxhc9@gitlab1.program.com.tw/BackendGroup/freshman/now/202307-james/comment.git