# .gitlab-ci.yml

# 定義工作階段（job）的執行環境
image: php:8.1

# 設定執行的階段
stages:
  - test

# 定義測試工作階段
test:
  stage: test
  script:
    - cp .env.example .env  # 將 .env.example 複製為 .env
    - composer install --no-interaction --prefer-dist  # 安裝 Composer 依賴
    - php artisan key:generate  # 生成 Laravel 應用程序密鑰
    - php artisan migrate --seed  # 遷移數據庫並填充種子數據
    - php artisan test  # 執行 Laravel 測試
