image: docker-hub.program.com.tw/nginx-php/php8.1-mongodb:dev

stages:
  - test

cs_test:
  stage: test
  tags:
    - docker
  script:
    - wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar --no-check-certificate
    - php phpcs.phar --standard=PSR12 --exclude=Generic.Files.LineLength,PSR12.Classes.OpeningBraceSpace --extensions=php app
