# .gitlab-ci.yml

# 定義工作階段（job）的執行環境
image: php:8.1

# 設定執行的階段
stages:
  - test

# 定義測試工作階段
test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y zip unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cp .env.example .env
    - composer install --no-ansi --no-interaction --no-progress --optimize-autoloader
    - php artisan key:generate
    - php artisan config:cache
    - php artisan migrate --force
    - vendor/bin/phpunit

# 您可以根據需求添加其他工作階段，例如部署階段等。
