image: docker-hub.program.com.tw/bikonnect-pluspay/php8.1-mongodb:dev

stages:
  - echo
  - test
  - deploy

echo_token:
  stage: echo
  script:
  - echo ${ACCESS_TOKEN}
  - echo $ACCESS_TOKEN

cs_test:
  stage: test
  tags:
    - docker
  before_script:
  - apt-get update
  - apt-get install -y ssh
  script:
    - php-cs-fixer fix app/

ci_commit:
  stage: deploy
  tags:
    - docker
  script:
  - git config user.email "james.huang@program.com.tw"
  - git config user.name "james.huang"
  - git remote add ff https://ACCESS_TOKEN:$ACCESS_TOKEN@gitlab1.program.com.tw/BackendGroup/freshman/now/202307-james/comment.git
  - git add .
  - git commit -m "push back from pipeline"
  - git push ff ci_test -o ci.skip
