image: docker-hub.program.com.tw/iotg-hub/php-gitlab-ci:latest

stages:
  - test

cs_test:
  stage: test
  tags:
    - docker
  before_script:
    - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  script:
    - php phpcs.phar --standard=./phpcs.xml --report=diff --report-full

