image: docker-hub.program.com.tw/bikonnect-pluspay/php8.1-mongodb:dev

stages:
  - test

before_script:
  - apk add --no-cache openssh-client

  # 創建一個用於存儲私鑰的文件
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa

  # 添加私鑰到 SSH 代理
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_rsa


cs_test:
  stage: test
  tags:
    - docker
  before_script:
  - apt-get update
  - apt-get install -y ssh
  script:
    - php-cs-fixer fix app/

    - git config user.email "james.huang@program.com.tw"
    - git config user.name "james.huang"
    - git remote add aa https://oauth2:$ACCESS_TOKEN@gitlab1.program.com.tw/BackendGroup/freshman/now/202307-james/comment.git
    - git add .
    - git commit -m "push back from pipeline"
    # - git checkout -b ci_test
    - git push aa ci_test -o ci.skip
